version: "3.5"

services: 
  app-service:
    build: ./docker
    container_name: app-container
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - DB_HOST=db-service
      - DB_PORT=3306
      - DB_DATABASE=db
      - DB_USERNAME=root
      - DB_PASSWORD=
    volumes: 
      - ./laravel:/var/www/html
    ports: 
      - "80:80"
    depends_on:
      - db-service
  db-service:
    image: mysql:5.7
    container_name: db-container
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
